version: '3.5'

services: 
  kotlin-restful-postgres:
    container_name: "arlite-restful"
    image: postgres:12-alpine
    ports: 
      - 5433:5432
    volumes:
      - .:/var/lib/my_data
    environment: 
      PGUSER: arlite
      POSTGRES_USER: arlite
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: arlite_restful
    restart: always